backend: 
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "assets"
    label: "Assets"
    folder: "src/components/md-store/assets"
    create: true
    editor: 
      preview: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Image", name: "image", widget: "image", allow_multiple: true}
  # - name: "settings"
  #   label: "Setting"
  #   create: true
  #   editor: 
  #     preview: true
  #   files:
  #     - label: "Contact Info"
  #       name: contact_info
  #       file: site/setttings/contact_info.json
  #       fields:
  #         - {label: "Name", name: "name", widget: "string"}
  #         - {label: "Year", name: "year", widget: "string"}

